name: PR validation
run-name: ${{ github.actor }} is running PR validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }} @ ${{ github.ref }}'

jobs:
  check:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🦀 Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: 📦 Cache
        uses: Swatinem/rust-cache@v2

      - name: 🎨 Format
        run: cargo fmt --check

      - name: 🧹 Lint
        run: cargo clippy --all-targets -- -D warnings

      - name: 🧪 Test
        run: cargo test
